#!/usr/bin/env php
<?php

(function() {
	foreach([__DIR__ . '/../../autoload.php', __DIR__ . '/../vendor/autoload.php', __DIR__ . '/vendor/autoload.php'] as $file) {
		if(file_exists($file)) {
			require_once $file;
			break;
		}
	}

	Poggit\Virion\Main::main();
})();
